# Waar is 'iets' in de buurt
# Datasource: sparql@https://api.labs.kadaster.nl/datasets/kadaster/kg/services/default/sparql
PREFIX brt: <https://brt.basisregistraties.overheid.nl/brt/def/>
PREFIX schema: <https://schema.org/>
PREFIX typeGebouw: <https://brt.basisregistraties.overheid.nl/brt/id/typeGebouw/>
SELECT ?address ?types ?polygon WHERE {
  {
    SELECT ?place ?address ?polygon (GROUP_CONCAT(DISTINCT STR(?type); SEPARATOR = ", ") AS ?types) WHERE {
      ?place (schema:additionalType/rdfs:label) "school"@nl;
        (schema:additionalType/rdfs:label) ?type;
        (schema:address/schema:name) ?address;
        (schema:containedInPlace/schema:name) "Rotterdam"@nl;
        (schema:geo/schema:polygon) ?polygon.
    }
  }
}
LIMIT 500

